
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button buttonClear;
	private global::Gtk.Button upperCase;
	private global::Gtk.Button lowerCase;
	private global::Gtk.Button Save;
	private global::Gtk.TextView textview1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.hbox1.Add (this.buttonClear);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonClear]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.upperCase = new global::Gtk.Button ();
		this.upperCase.CanFocus = true;
		this.upperCase.Name = "upperCase";
		this.upperCase.UseUnderline = true;
		this.upperCase.Label = global::Mono.Unix.Catalog.GetString ("Make Upper");
		this.hbox1.Add (this.upperCase);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.upperCase]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lowerCase = new global::Gtk.Button ();
		this.lowerCase.CanFocus = true;
		this.lowerCase.Name = "lowerCase";
		this.lowerCase.UseUnderline = true;
		this.lowerCase.Label = global::Mono.Unix.Catalog.GetString ("Make Lower");
		this.hbox1.Add (this.lowerCase);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lowerCase]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Save = new global::Gtk.Button ();
		this.Save.CanFocus = true;
		this.Save.Name = "Save";
		this.Save.UseUnderline = true;
		this.Save.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.hbox1.Add (this.Save);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Save]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.vbox1.Add (this.textview1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.textview1]));
		w6.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		this.upperCase.Clicked += new global::System.EventHandler (this.OnUpperCaseClicked);
		this.lowerCase.Clicked += new global::System.EventHandler (this.OnLowerCaseClicked);
		this.Save.Clicked += new global::System.EventHandler (this.OnSaveClicked);
	}
}
